### ISSUE TITLE
Not all videos are being shown. 

### ISSUE THREAD

**Issue by Aeres-u99** [matthuisman/plugin.video.udemy#1]
In the latest version of Udemy addon, not all videos are being shown in kodi. 
That is, if someone has courses over 100 in number then only the oldest 100 will be shown. 
for now, as temporary solution I have switched back to the older version 0.0.1.

**Comment by matthuisman** [comment]
@Aeres-u99 
Just pushed version 0.7.5 that adds pagination.
Should fix your issue

**Comment by Aeres-u99** [comment]
checked. Working well and proper, thank you ^_^
